// <auto-generated />
namespace CRUDWithImage.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Fourthone : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fourthone));
        
        string IMigrationMetadata.Id
        {
            get { return "202406210248352_Fourth one"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
